version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - PORT=8000
    restart: unless-stopped